### ISSUE TITLE
How can I add animation or effect when using scroll directive ?

### ISSUE THREAD

**Issue by rainstormza** [MarcinMichalik/ng-scrollTo#1]
How can I add animation or effect when using scroll directive ?

thanks

**Comment by MarcinMichalik** [comment]
I add simple animation using ```window.requestAnimationFrame();``` - check browser support (https://developer.mozilla.org/pl/docs/Web/API/Window/requestAnimationFrame). You can only change duration this animation by ``` [scrollDuration]="1000"```.
In my free time I improve this module.
