### ISSUE TITLE
don't throw error when the scrolling fail

### ISSUE THREAD

**Issue by sinsunsan** [MarcinMichalik/ng-scrollTo#4]
When the element to be scrolled do not exist you throw an error 
https://github.com/MarcinMichalik/ng-scrollTo/blob/master/src/scrollTo.service.ts#L23

I don't think this error is important enough to break the code of people using your service...
Why don't you use promise or observable to get the service to know the error or a simple console.error or console.log to have the developer know about it.

So temporarly I used this try / catch block 

````js
this.route.fragment.subscribe((fragment: string) => {
      try {
         this.scrollService.scrollTo(fragment);
      }
      catch (e) {
         console.log('error at scrolling to ', fragment)
      }
    });
````

**Comment by MarcinMichalik** [comment]
Thanks for comments and tip. I release new version and replace throw with Observable.
